# Generated by Django 3.2.4 on 2021-06-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistifordogs',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vistifordogs',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
